package edu.udacity.java.nano.chat.ex;

import org.springframework.core.NestedRuntimeException;

public class AppException extends NestedRuntimeException {

  /* constants */
  /** Generated by eclipse */
  private static final long serialVersionUID = -3325969365121958771L;

  
  /* member variables */

  
  /* constructors */
  public AppException(String msg, Throwable cause) {
    super(msg, cause);
  }

  public AppException(String msg) {
    super(msg);
  }

  /* methods */

}
